# Gradle
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

org.gradle.caching=false
org.gradle.parallel=false

# Allow switching between flavors of the Jellyfin SDK. Possible values are:
# - "default"
# - "local" (local Maven repository)
# - "snapshot" (SDK master)
# - "unstable-snapshot" (SDK with unstable Jellyfin API)
sdk.version=default
